import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Head from "next/head";
import CartProvider from "./components/Providers";
import ShoppingCartModel from "./components/ShoppingCartModel";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "NutriEdge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Standard favicon */}
        <link rel="icon" href="/favicon.ico" />

        {/* PNG Fallback */}
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />

        {/* Apple Touch Icon */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />

        {/* Android Chrome Icon */}
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <body
>
  <CartProvider>
    <Navbar />
    <main className="mt-[80px]">{children}</main> {/* Push content down */}
    <Footer />
    <ShoppingCartModel />
  </CartProvider>
</body>
    </html>
  );
}
